// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPVadyMdGhk9gGjhpQbvJDaXXjFlv-39I',
    appId: '1:331143669886:web:215d687f8d57ed3181902f',
    messagingSenderId: '331143669886',
    projectId: 'smart-parking-fd456',
    authDomain: 'smart-parking-fd456.firebaseapp.com',
    databaseURL: 'https://smart-parking-fd456-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-parking-fd456.firebasestorage.app',
    measurementId: 'G-M7VPK3JDVH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJ0h8JJh6_5-dbTyJrP2hfhWXciuwO35Y',
    appId: '1:331143669886:android:cd0c1508cb60c75d81902f',
    messagingSenderId: '331143669886',
    projectId: 'smart-parking-fd456',
    databaseURL: 'https://smart-parking-fd456-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-parking-fd456.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPVadyMdGhk9gGjhpQbvJDaXXjFlv-39I',
    appId: '1:331143669886:web:d165a17e7025d16581902f',
    messagingSenderId: '331143669886',
    projectId: 'smart-parking-fd456',
    authDomain: 'smart-parking-fd456.firebaseapp.com',
    databaseURL: 'https://smart-parking-fd456-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-parking-fd456.firebasestorage.app',
    measurementId: 'G-6B8SH7N8RX',
  );
}
